dpkg: warning: files list file for package 'bind9-host' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'baobab' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'aptdaemon-data' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt-transport-https' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'aisleriot' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'base-passwd' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bash' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'build-essential' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt-config-icons-hidpi' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt-utils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'alsa-base' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bash-completion' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bluez-cups' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'at-spi2-core' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'acpi-support' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bsdutils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'adium-theme-ubuntu' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt-xapian-index' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apparmor' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apport-gtk' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'appstream' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apturl' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apg' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bzip2' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'app-install-data-partner' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'avahi-daemon' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'binutils-common:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'busybox-initramfs' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bolt' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'base-files' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'acpid' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bubblewrap' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apturl-common' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'alsa-utils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'btrfs-progs' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'aptdaemon' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bluez-obexd' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'aspell-en' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apport-symptoms' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'avahi-utils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apport' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'avahi-autoipd' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'breeze-icon-theme' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'binutils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'busybox-static' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'brltty' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'accountsservice' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'apt-config-icons' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bsdmainutils' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'anacron' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bc' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'aspell' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'adduser' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'bluez' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'acl' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'amd64-microcode' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'branding-ubuntu' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'adwaita-icon-theme' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'binutils-x86-64-linux-gnu' missing; assuming package has no files currently installed
